project: 
  type: website
  output-dir: docs

website:
  title: "Brassard, Presse & Chevalier, 2024"
  navbar:
    background: primary
    search: true
    left:
    - text: "READ ME"
      href: "https://github.com/didierbrassard/NuAge_protocol/blob/main/README.md"
    - icon: database-fill
      text: "Data preparation"
      file: 1.0-Data_preparation.R
    - text: "Manuscript"
      file: 9.1-Manuscript.qmd
    - text: "Supplement"
      file: 9.2-Supplement.qmd
    right:
    - icon: envelope
      text: Email
      href: "mailto:didier.brassard@mcgill.ca"

format:
  html: 
    theme: Journal
    toc: true
