project: 
  type: website
  output-dir: docs

website:
  title: "Brassard, Presse & Chevalier, 2024"
  navbar:
    background: primary
    search: true
    left:
    - text: "READ ME"
      href: "https://github.com/didierbrassard/NuAge_protocol/blob/main/README.md"
    - text: "Manuscript"
      file: 9.1-Manuscript.qmd
    - text: "Supplemental material"
      file: 9.2-Supplement.qmd
    - icon: database-fill
      text: Access data
      href: google.ca
    right:
    - icon: envelope
      text: Email
      href: "mailto:didier.brassard@mcgill.ca"
    - icon: twitter
      text: Twitter
      href: https://twitter.com/didier_dtp

format:
  html: 
    theme: Journal
    toc: true